=== fvilarinho/framework/src/main/resources/etc/resources/factoryResources.xsd
<xs:schema elementFormDefault="qualified"
           xmlns:xs="http://www.w3.org/2001/XMLSchema">
 	<xs:element name="factory">
    	<xs:complexType>
      		<xs:sequence>
        		<xs:element name="ldap">
          			<xs:complexType>
            			<xs:sequence>
              				<xs:element name="resources" maxOccurs="unbounded">
                				<xs:complexType>
                  					<xs:sequence>
					                    <xs:element type="xs:string" name="class"/>
					                    <xs:element type="xs:string" name="uri"/>
									</xs:sequence>
                  					<xs:attribute type="xs:string" name="id" use="required"/>
                  					<xs:attribute type="xs:boolean" name="default"/>
                				</xs:complexType>
              				</xs:element>
            			</xs:sequence>
          			</xs:complexType>
        		</xs:element>
        		<xs:element name="persistence">
          			<xs:complexType>
            			<xs:sequence>
              				<xs:element name="resources" maxOccurs="unbounded">
                				<xs:complexType>
                  					<xs:sequence>
                    					<xs:element type="xs:string" name="class"/>
                    					<xs:element type="xs:string" name="uri"/>
                  					</xs:sequence>
                  					<xs:attribute type="xs:string" name="id" use="required"/>
                  					<xs:attribute name="type" use="required">
										<xs:simpleType>
										    <xs:restriction base="xs:string">
										        <xs:enumeration value="MSSQL"/>
										        <xs:enumeration value="SYBASE"/>
										        <xs:enumeration value="DB2"/>
										        <xs:enumeration value="ORACLE"/>
										        <xs:enumeration value="MYSQL"/>
										        <xs:enumeration value="POSTGRESQL"/>
										        <xs:enumeration value="FIREBIRD"/>
										        <xs:enumeration value="INFORMIX"/>
										    </xs:restriction>
										</xs:simpleType>
                  					</xs:attribute>
                  					<xs:attribute type="xs:boolean" name="default"/>
                				</xs:complexType>
              				</xs:element>
            			</xs:sequence>
          			</xs:complexType>
        		</xs:element>
      		</xs:sequence>
    	</xs:complexType>
  	</xs:element>
</xs:schema>

=== fvilarinho/framework/src/main/resources/etc/resources/factoryResources.xml
<?xml version="1.0" encoding="utf-8"?>
 
<factory xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="factoryResources.xsd">
	<ldap>
		<resources id="ldap" default="true">
			<class>com.sun.jndi.ldap.LdapCtxFactory</class>
			<uri>ldap://#{serverName}:#{serverPort}/#{baseDn}</uri>
		</resources>
	</ldap>
	<persistence>
        <resources id="h2" type="H2" default="true">
            <class>org.h2.Driver</class>
            <uri>jdbc:h2:mem:#{repositoryId}</uri>
        </resources>
        <resources id="mssql" type="MSSQL">
			<class>net.sourceforge.jtds.jdbc.Driver</class>
			<uri>jdbc:jtds:sqlserver://#{serverName}:#{serverPort}/#{repositoryId}</uri>
		</resources>
		<resources id="sybase" type="SYBASE">
			<class>net.sourceforge.jtds.jdbc.Driver</class>
			<uri>jdbc:jtds:sybase://#{serverName}:#{serverPort}/#{repositoryId}</uri>
		</resources>
		<resources id="db2" type="DB2">
			<class>COM.ibm.db2.jdbc.app.DB2Driver</class>
			<uri>jdbc:db2://#{serverName}:#{serverPort}/#{repositoryId}</uri>
		</resources>
		<resources id="oracle" type="ORACLE">
			<class>oracle.jdbc.driver.OracleDriver</class>
			<uri>jdbc:oracle:thin:@#{serverName}:#{serverPort}:#{repositoryId}</uri>
		</resources>
		<resources id="mysql" type="MYSQL">
			<class>com.mysql.cj.jdbc.Driver</class>
			<uri>jdbc:mysql://#{serverName}:#{serverPort}/#{repositoryId}?autoReconnectForPools=true&amp;failOverReadOnly=false&amp;useSSL=false&amp;useUnicode=true&amp;characterEncoding=UTF-8</uri>
		</resources>
		<resources id="postgresql" type="POSTGRESQL">
			<class>org.postgresql.Driver</class>
			<uri>jdbc:postgresql://#{serverName}:#{serverPort}/#{repositoryId}</uri>
		</resources>
		<resources id="firebird" type="FIREBIRD">
			<class>org.firebirdsql.jdbc.FBDriver</class>
			<uri>jdbc:firebirdsql://#{serverName}:#{serverPort}/#{repositoryId}</uri>
		</resources>
		<resources id="informix" type="INFORMIX">
			<class>com.informix.jdbc.IfxDriver</class>
			<uri>jdbc:informix-sqli://#{serverName}:#{serverPort}/#{repositoryId}:informixserver=#{instanceId}</uri>
		</resources>
	</persistence>
</factory>
