=== fvilarinho/framework/src/main/resources/etc/resources/persistenceResources.xsd
<xs:schema elementFormDefault="qualified"
           xmlns:xs="http://www.w3.org/2001/XMLSchema">
 	<xs:element name="persistence">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="resources" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element type="xs:string" name="serverName" minOccurs="0"/>
                            <xs:element type="xs:string" name="serverPort" minOccurs="0"/>
                            <xs:element type="xs:string" name="instanceId" minOccurs="0"/>
                            <xs:element type="xs:string" name="repositoryId"/>
							<xs:element type="xs:string" name="userName" minOccurs="0"/>
							<xs:element type="xs:string" name="password" minOccurs="0"/>
							<xs:element name="options" minOccurs="0">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="option" maxOccurs="unbounded">
											<xs:complexType>
												<xs:simpleContent>
													<xs:extension base="xs:string">
														<xs:attribute type="xs:string" name="id" use="required"/>
														<xs:attribute type="xs:string" name="value" use="required"/>
													</xs:extension>
												</xs:simpleContent>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute type="xs:string" name="id" use="required"/>
						<xs:attribute type="xs:string" name="factoryResourcesId"/>
						<xs:attribute type="xs:boolean" name="default"/>
					</xs:complexType>
				</xs:element>
				<xs:element name="mappings" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element type="xs:string" name="mapping" minOccurs="0" maxOccurs="unbounded"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>			
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== fvilarinho/framework/src/main/resources/etc/resources/persistenceResources.xml
<?xml version="1.0" encoding="utf-8"?>

<persistence xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="persistenceResources.xsd">  
    <resources id="datasource" factoryResourcesId="h2" default="true">
        <repositoryId>test</repositoryId>  
        <userName>root</userName>  
        <options>
            <option id="hibernate.cache.use_minimal_puts" value="false"/>
            <option id="hibernate.cache.use_query_cache" value="true"/>
            <option id="hibernate.cache.use_second_level_cache" value="true"/>
            <option id="hibernate.cache.region.factory_class" value="org.hibernate.cache.jcache.JCacheRegionFactory"/>
            <option id="hibernate.cache.provider_class" value="org.ehcache.jsr107.EhcacheCachingProvider"/>
            <option id="hibernate.current_session_context_class" value="thread"/>
            <option id="hibernate.format_sql" value="false"/>
            <option id="hibernate.generate_statistics" value="false"/>
            <option id="hibernate.jdbc.time_zone" value="UTC"/>
            <option id="hibernate.query_maximum_results" value="3000"/>
            <option id="hibernate.show_sql" value="false"/>
            <option id="hibernate.dialect.storage_engine" value="innodb"/>
            <option id="hibernate.dbcp.initialSize" value="5"/>
            <option id="hibernate.dbcp.maxTotal" value="20"/>
            <option id="hibernate.dbcp.maxIdle" value="10"/>
            <option id="hibernate.dbcp.minIdle" value="5"/>
            <option id="hibernate.dbcp.maxWaitMillis" value="1"/>
            <option id="hibernate.hbm2ddl.auto" value="update"/>
        </options> 
    </resources>
    <mappings/>
</persistence>
