=== fvilarinho/framework/src/main/resources/etc/resources/systemResources.xsd
<xs:schema elementFormDefault="qualified"
           xmlns:xs="http://www.w3.org/2001/XMLSchema">
 	<xs:element name="resources">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="mainConsole">
					<xs:complexType>
						<xs:sequence>
							<xs:element type="xs:string" name="class" minOccurs="0"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="languages">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="language" maxOccurs="unbounded">
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:string">
											<xs:attribute type="xs:string" name="id" use="required"/>
											<xs:attribute type="xs:boolean" name="default"/>
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="skins">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="skin" maxOccurs="unbounded">
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:string">
											<xs:attribute type="xs:string" name="id" use="required"/>
											<xs:attribute type="xs:boolean" name="default"/>
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="actionForms" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="actionForm" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="forwards">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="forward" maxOccurs="unbounded">
														<xs:complexType>
															<xs:simpleContent>
																<xs:extension base="xs:string">
																	<xs:attribute type="xs:string" name="name" use="required"/>
																	<xs:attribute type="xs:string" name="url" use="required"/>
																</xs:extension>
															</xs:simpleContent>
														</xs:complexType>
													</xs:element>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
									<xs:attribute type="xs:string" name="name" use="required"/>
									<xs:attribute type="xs:string" name="action" use="required"/>
									<xs:attribute type="xs:string" name="class" use="required"/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="services" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="service" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:string">
											<xs:attribute type="xs:string" name="path"/>
											<xs:attribute type="xs:boolean" name="isDaemon"/>
											<xs:attribute type="xs:boolean" name="isRecurrent"/>
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== fvilarinho/framework/src/main/resources/etc/resources/systemResources.xml
<?xml version="1.0" encoding="UTF-8"?>

<resources xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="systemResources.xsd">
    <mainConsole/>
    <languages>
        <language id="pt_BR" default="true"/>
        <language id="en_US"/>
        <language id="es"/>
    </languages>  
    <skins>
        <skin id="default" default="true"/>
    </skins>  
    <actionForms/> 
    <services/> 
</resources>
